### ISSUE TITLE
Wrap 401 responses and re-login.

### ISSUE THREAD

**Issue by RussellMcOrmond** [crkn-rcdr/CIHM-Swift#13]
Scripts are regularly exiting with errors like:

```
container_get(repository) returned 401 - Unauthorized
 at /home/tdr/CIHM-TDR/bin/tdr-swiftreplicate line 29.
```

Is it possible to handle 401 internal to the module so that it will get a new token to use for further requests?

**Comment by RussellMcOrmond** [comment]
Whatever is happening, it seems to happen at the same time for all processes talking to Swift.  I had an instance where 8 threads on one computer and a separate program on another (different province) all got a 401 response at about the same time.

**Comment by SaschaAdler** [comment]
The above commit should help with this. Let me know how it goes.

**Comment by RussellMcOrmond** [comment]
I tried building a new container that only had the new updates, and got:

```
2019/08/16 07:29:55 - ERROR {CIHM.TDR} [CIHM::TDR::SwiftReplicateWorker::catch {...} ] carl.AEU_19691020: container_get(repository) for carl.AEU_19691020 returned 500 
- Internal Response: Unexpected EOF while reading response header at /home/tdr/CIHM-Swift/lib/CIHM/Swift/Client.pm line 208.

 at /home/tdr/CIHM-TDR/bin/../lib/CIHM/TDR/SwiftReplicateWorker.pm line 73.

```

I reverted to the previous container, and can look into it in more detail next week.

**Comment by SaschaAdler** [comment]
Interesting. Did this happen instantly, or is it just a different intermittent error?

**Comment by RussellMcOrmond** [comment]
This seems to be working well -- it wasn't instant, but happened periodically (possibly when something was restarted on the server, etc).  I haven't seen this problem since the update.
