### ISSUE TITLE
Need to increase timeout in Furl options.

### ISSUE THREAD

**Issue by RussellMcOrmond** [crkn-rcdr/CIHM-Swift#14]
I tried passing "timeout => 60 in options to `CIHM::Swift::Client->new(%swiftopt)` , but note that parameters passed into this module aren't passed via `return Furl->new();`

The 10 second timeout isn't long enough for the larger PDF files that need to be sent with some AIPs.

```
2019/08/13 11:49:56 - WARN {CIHM.TDR} [CIHM::TDR::Swift::replicateaip] object_put of oocihm.8_06912_140/data/sip/data/files/oocihm.8_06912_140.pdf returned:500 - Internal Response: Failed to send content: timeout at /home/tdr/CIHM-Swift/lib/CIHM/Swift/Client.pm line 196.

```

**Comment by SaschaAdler** [comment]
You can now set `furl_options => { timeout => 60 }` in the `CIHM::Swift::Client` constructor.

**Comment by RussellMcOrmond** [comment]
The timeout setting worked -- sending from Ottawa to Edmonton I needed to increase the timeout further to 120 seconds.

I got the unauthorized, which is #13 , but this one can close.  Thanks!

```
tdr@f24cff209363:~$ tdr-swiftreplicate --aip=oocihm.8_06912_140 --verbose
Put oocihm.8_06912_140/manifest-crc32.txt
Put oocihm.8_06912_140/manifest-md5.txt
Put oocihm.8_06912_140/bag-info.txt
Put oocihm.8_06912_140/bagit.txt
Put oocihm.8_06912_140/data/sip/data/files/oocihm.8_06912_140.pdf
container_get(repository) returned 401 - Unauthorized
 at /home/tdr/CIHM-TDR/bin/tdr-swiftreplicate line 29.
```
