### ISSUE TITLE
Can't determine mimeTypeOf($object)

### ISSUE THREAD

**Issue by RussellMcOrmond** [crkn-rcdr/CIHM-Swift#15]
The following error was noted in the cron email:

```
Can't call method "type" on an undefined value at /home/tdr/CIHM-Swift/lib/CIHM/Swift/Client.pm line 197.
```

**Comment by SaschaAdler** [comment]
There's a bug in how it's implemented, but this is related to a file with no extension (and therefore no MIME type) being uploaded. I'm setting the `Content-Type` header to `application/octet-stream` when this happens.

**Comment by SaschaAdler** [comment]
The new test in the commit should handle this issue. Happy to re-open if it doesn't.
