### ISSUE TITLE
Discussion: Access Object policy

### ISSUE THREAD

**Issue by RussellMcOrmond** [crkn-rcdr/CIHM-Swift#2]
A place to discuss https://github.com/crkn-rcdr/CIHM-Swift/wiki/Access-Object-policy

**Comment by RussellMcOrmond** [comment]
* "Manifests may have PDFs associated with them. This process is derivative and should not violate immutability constraints."

Manifests and Images may have PDFs associated with them.

There will be many manifests which, for a variety of reasons (such as list too long), that won't have a derived multi-page PDF, but the single-page PDFs still exist and should be possible to access via the access platform.

These single-page PDFs are associated with and derived from Images, not necessarily a canvas.

**Comment by RussellMcOrmond** [comment]
* "Policy question: What happens to the public metadata record when a manifest or collection has, e.g., a MARC and a DC record?"

I'm a fan of thinking of the metadata record as a single thing, regardless of format or content.  If a record previously had a DC record, and a MARC record is created, the DC record is no longer considered a current record any more than a record with a different description would be considered current.

The record in the preservation platform can be seen as something to prime the access platform, but there is no necessity to retain a reference to (or copy of) the preservation platform record within the access platform.



* "Policy question: Do we need to keep track of multiple OCR outputs for a given canvas?"

I'm always going to be stuck on this language, as OCR is done against an image (OCR software knows nothing about IIIF).

If the image was generated from a canvas (IE: possibly multiple images/etc annotating a canvas) then it can be seen as an OCR of a canvas.

Otherwise, we are doing OCR on independent image files which may or may annotate zero or more canvasses.

Policy question thoughts: currently the only reason we would have a second OCR is if we replaced a PrimeOCR with an Abbyy recognition server file.  This is in a separate SIP, and as far as I know the access platform was never intended to reach into the history of an AIP to look at what might have been in a previous SIP. Therefore there is only ever a single OCR available.

I'd have to do analysis to see if any example exists of multiple OCR within different SIPs in the preservation platform -- I suspect not, as the project to upgrade past OCR hasn't really started.

If in the future there is some purpose to layering machine generated transcription (allowing users to toggle between/etc), then that can be thought of as a future feature enhancement.

**Comment by RussellMcOrmond** [comment]
I'm trying to wrap my head around how we will represent a canvas which has multiple images (other canvasses) annotated onto it.

Should I be thinking of there being different types of canvases: one that can only contain a single source image annotated on it (the image and that canvas having the same ID).  This would then be separate from a canvas which instead of referencing images directly would only reference other canvasses.

If the image file had a CanvasID, then the associated OCR (PDF and XML) also being linked to that CanvasID would make sense to me.

I'm wanting to ensure that as we move forward we don't use terminology and identifiers that lock us into only being able to support the same features we have today.

**Comment by nataliemacdonald** [comment]
"Policy question: What happens to the public metadata record when a manifest or collection has, e.g., a MARC and a DC record?"

Separate from how you decide to present the data, I think grabbing it from Marc records, when available, is the best. All manifests should have an associated Marc record. If no Marc record exists then it grabs from DC? But, I don't know if I understand the situation where a manifest doesn't have a Marc record. Generally, Marc is more robust than DC, so it should theoretically capture all of the information that would be in a DC record. 

Are you going to be grabbing the descriptive metadata records from the current system? Or, is there a possibility to take the records in Marc format from elsewhere? It would be great if we could implement a system that takes the records from .mrc or .mrk files that we create because (maybe) it would allow for the metadata to be more easily updated by re-uploading the updated Marc file? Again, I have no idea if these requests are feasible for the programming side of things. 

I hope this makes sense.

**Comment by RussellMcOrmond** [comment]
@nataliemacdonald 

For when you return I will have statistics on the number of existing "manifests" that have MARC, DC or issueinfo (derivative of DC).  I don't know the percentages offhand, but I wouldn't be surprised if a majority of what will become manifests don't have MARC records.

Now, if MARC records have been created since ingest, and weren't added to the platform, that isn't something we would know.  Loading new metadata will be easier in the new platform, so making these updates will be more likely.


Related:

@SaschaAdler at one point was talking about a descriptive metadata editor rather than a descriptive metadata manager (loading/saving, and initiating processing).  I still believe we would be better off thinking of descriptive metadata editing as being outside of our platform, with MarcEdit being the one we use in testing.  This came up at a PAC or PTTG meeting, and one of the members suggested that editing would be complex without a commensurate return.

Missing is something to aid in the editing/validating/etc of Dublin Core, which might be worth considering a simple editor for to improve on the CSV in/out at some later point.

**Comment by RussellMcOrmond** [comment]
This type of conversation moved into https://github.com/crkn-rcdr/Access-Platform/discussions

I'm closing, but if anyone thinks we missed something we can open a new discussion (and hopefully remember to close when we think we are complete).
