### ISSUE TITLE
Initialize the client with an account separate from the user's

### ISSUE THREAD

**Issue by SaschaAdler** [crkn-rcdr/CIHM-Swift#5]
In the event we need to access some other user's containers, assuming our account has been granted ACL access.

**Comment by SaschaAdler** [comment]
I've assigned this to Russell, as I cannot test this functionality with `picoswiftstack` and we should keep the issue open until this is confirmed to work.

**Comment by RussellMcOrmond** [comment]
For replication to AUTH_crkn/repository I am making use of this feature and it works well.
